from rdflib import Namespace

ANDS = Namespace(u'http://www.ands.org.au/ontologies/ns/0.1/VITRO-ANDS.owl#')
MARCREL = Namespace(u'http://www.loc.gov/loc.terms/relators/')
VIVO = Namespace(u'http://vivoweb.org/ontology/core#')
CLD = Namespace(u'http://purl.org/cld/terms/')
FOR08 = Namespace(u'http://purl.org/asc/1297.0/2008/for/')
DC = Namespace(u'http://purl.org/dc/terms/')
DCES = Namespace(u'http://purl.org/dc/elements/1.1/')
BIBO = Namespace(u'http://purl.org/ontology/bibo/')
SEO08 = Namespace(u'http://purl.org/asc/1297.0/2008/seo/')
SEO98 = Namespace(u'http://purl.org/asc/1297.0/1998/seo/')
RDFS = Namespace(u'http://www.w3.org/2000/01/rdf-schema#')
FOAF = Namespace(u'http://xmlns.com/foaf/0.1/')
GUHUBEXT = Namespace(u'http://griffith.edu.au/ontology/hubextensions/')
RDF = Namespace(u'http://www.w3.org/1999/02/22-rdf-syntax-ns#')
SKOS = Namespace(u'http://www.w3.org/2004/02/skos/core#')
RFCD = Namespace(u'http://purl.org/asc/1297.0/1998/rfcd/')
